name: Promote Staging to Production
permissions:
  id-token: write
  contents: true
  pull-requests: write
  issues: write
  repository-projects: write
on: 
  workflow_dispatch:
    branches: [main]
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Batch changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: batch auto
      - name: Merge changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: merge
      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: latest
      - uses: stefanzweifel/git-auto-commit-action@v6
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: Bump Version to ${{ steps.latest.outputs.output }}
          tagging_message: '${{ steps.latest.outputs.output }}'