name: Promote Staging to Production
permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
on: 
  workflow_dispatch:
    branches: [production]
jobs:
  commit-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge Fast Forward
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: main
          # Branch that will be updated
          branch: production
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Batch changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: batch auto
      - name: Merge changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: merge
      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: latest
      - name: Get the latest version
        id: diff
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: diff 1
      - uses: stefanzweifel/git-auto-commit-action@v6
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: Bump Version to ${{ steps.latest.outputs.output }}
      - name: Merge Fast Forward
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: production
          # Branch that will be updated
          branch: main
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Slack Markdown Converter
        uses: LoveToKnow/slackify-markdown-action@v1.1.1
        id: slackconvert
        with:
          text: ${{ steps.diff.outputs.output }}
      - name: Send Message to Slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "New Test REPO Release: ${{ steps.latest.outputs.output }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "New Test REPO Release: ${{ steps.latest.outputs.output }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.slackconvert.outputs.text }}"
  deploy:
    needs: commit-new-version
    uses: ./.github/workflows/terraform-deploy.yml